

chinese_map = {
    'label_6': '【PC端口参数】',
    'label_7': '串口',
    'label_8': '波特率',
    'label_9': '数据位/校验位/停止位',
    'cloud_type_txt': '云平台通信类型',
    'fota_txt': '固件升级',
    'sota_txt': '脚本升级',
    'filter_txt': '透传数据过滤设置',
    'history_txt': '历史数据存储',
    'uart_config_txt': '串口参数配置',
    'uart_port_txt': '串口号',
    'baudrate_txt': '波特率',
    'databits_txt': '数据位',
    'parity_txt': '校验位',
    'stopbits_txt': '停止位',
    'flowctl_txt': '流控',
    'rs485_pin_txt': '控制485通信方向Pin',
    'yun_config_txt': '云参数配置---------------------',
    'clear_recv_button': '清空',
    'clear_send_button': '清空发送',
    'send_button': '发送',
    'clear_button': '清空',
    'get_now_setting_button': '获取当前参数',
    'save_setting_button': '保存所有设置参数并重启',
    'restore_factory_setting_button': '恢复出厂参数设置并重启',
    'query_imei_button': '查询IMEI',
    'query_phone_num_button': '查询本机号码',
    'query_signal_strength_button': '查询信号强度',
    'restart_button': '设备重启',
    'cloud_type_combo_box': ["阿里云", "腾讯云", "华为云", "移远云", "TCP私有云", "MQTT私有云"],
    'fota_combo_box': ["关闭", "开启"],
    'sota_combo_box': ["关闭", "开启"],
    'offline_storage_combo_box': ["关闭", "开启"],
}


english_map = {
    'label_6': '【PC settings】',
    'label_7': 'serial',
    'label_8': 'baudrate',
    'label_9': 'databits/parity/stopbits',
    'cloud_type_txt': 'clound type',
    'fota_txt': 'fota',
    'sota_txt': 'sota',
    'filter_txt': 'filter',
    'history_txt': 'history',
    'uart_config_txt': 'uart config',
    'uart_port_txt': 'port',
    'baudrate_txt': 'baudrate',
    'databits_txt': 'databits',
    'parity_txt': 'parity',
    'stopbits_txt': 'stopbits',
    'flowctl_txt': 'flowctl',
    'rs485_pin_txt': 'control rs485 pin',
    'yun_config_txt': 'cloud settings---------------------',
    'clear_recv_button': 'clear',
    'clear_send_button': 'clear',
    'send_button': 'send',
    'clear_button': 'clear',
    'get_now_setting_button': 'get current setting',
    'save_setting_button': 'save setting',
    'restore_factory_setting_button': 'restore factory setting',
    'query_imei_button': 'imei',
    'query_phone_num_button': 'phone number',
    'query_signal_strength_button': 'signal strength',
    'restart_button': 'restart',
    'cloud_type_combo_box': ["aliyun", "txyun", "huawei", "quectel", "TCP", "MQTT"],
    'fota_combo_box': ["off", "on"],
    'sota_combo_box': ["off", "on"],
    'offline_storage_combo_box': ["off", "on"]
}
